data=[
    {
    "id":"1",
    "name":"MERSATI",
    "src":"./images/logo/MERSATI.png"
    },
    {
        "id":"2",
        "name":"BENTLEY",
        "src":"./images/logo/BENTLEY.png"
     },
     {
        "id":"3",
        "name":"HONDA",
        "src":"./images/logo/HONDA.png"
     },
      {
        "id":"4",
        "name":"TOYOTA",
        "src":"./images/logo/TOYOTA.png"
     },
     {
        "id":"5",
        "name":"INFENTI",
        "src":"./images/logo/INFENTI.png"
     },
      {
        "id":"6",
        "name":"FORD",
        "src":"./images/logo/FORD.png"
     },
     {
        "id":"7",
        "name":"JEEB",
        "src":"./images/logo/JEEB.png"
     },
     {
        "id":"8",
        "name":"VOLKWAGEN",
        "src":"./images/logo/VOLKWAGEN.png"
     },
     {
        "id":"9",
        "name":"OPEL",
        "src":"./images/logo/OPEL.png"
     },
     {
        "id":"10",
        "name":"AUDI",
        "src":"./images/logo/AUDI.png"
     },
     {
        "id":"11",
        "name":"FIAT",
        "src":"./images/logo/FIAT.png"
     },
     {
        "id":"12",
        "name":"GMC",
        "src":"./images/logo/GMC.png"
     },
     {
        "id":"13",
        "name":"NISAN",
        "src":"./images/logo/NISAN.png"
     },
     {
        "id":"14",
        "name":"KIA",
        "src":"./images/logo/KIA.png"
     }


];

models=[
   {
    "id":"1",
    "name":"s1"
   },
   {
      "id":"2",
      "name":"s2"
     },
     {
      "id":"3",
      "name":"s3"
     },
     {
      "id":"4",
      "name":"s4"
     },
     {
      "id":"5",
      "name":"s5"
     },
     {
      "id":"6",
      "name":"s6"
     }
]
